# python3 parse_by_time_all.py --accuracy=12 --from_to=from &
# python3 parse_by_time_all.py --accuracy=12 --from_to=to &
# python3 parse_by_time_all.py --accuracy=13 --from_to=from &
# python3 parse_by_time_all.py --accuracy=13 --from_to=to &
python3 parse_by_time_all.py --epoch_num=5 --accuracy=12 --from_to=from &
python3 parse_by_time_all.py --epoch_num=5 --accuracy=12 --from_to=to &
python3 parse_by_time_all.py --epoch_num=5 --accuracy=13 --from_to=from &
python3 parse_by_time_all.py --epoch_num=5 --accuracy=13 --from_to=to &
python3 parse_by_time_all.py --epoch_num=5 --accuracy=14 --from_to=from &
python3 parse_by_time_all.py --epoch_num=5 --accuracy=14 --from_to=to &
python3 parse_by_time_all.py --epoch_num=5 --accuracy=11 --from_to=from &
python3 parse_by_time_all.py --epoch_num=5 --accuracy=11 --from_to=to &
